### ISSUE TITLE
Question: Is this lib duplex capable?

### ISSUE THREAD

**Issue by nirmalnirav** [trteodor/DLTuc_lib#2]
Hello trteodor,
1. I find the project very appealing. I have used DLT_Viewer intensive at work and often miss the features in embedded development. Thanks for the open source project.
2. Could you please inform me, whether this lib is capable to send Characters from the DLT_Viewer to the micro controller? The DLT Protocol can change the log level or send a flag to the target/ device. Is it possible to use this method to send messages to the microcontroller?
3. If you need some assistance in implementing it, I am ready to collaborate :)

Thanks and regards
Nirav

**Comment by trteodor** [comment]
Hi nirmalnirav,
1. Thanks for postivie feedback!
2. Sorry, current implementation is capable only to transmit DLT messages from MCU. Design  and current state of code is very simple for integration and should be usable. Nevertheless to use the library in true commercial project some re-works maybe required. 
I don't predicted even receive handler... As remember it should be very easy to handle most of messages / commands transmitted to microcontroller from Dlt Viewer.  
3. If you are eager to collaborate with the implementation, then OK, let's try! We should then orgranize meeting, exchange our ideas then we can try to develop this library. My frist suggestion to orgranize meeting is Discord channel, I'am also open for change requests...

**Comment by nirmalnirav** [comment]
Hello Teodor,
thanks for the quick response. I am willing to contribute to this project, but I have no knowledge of the DLT protocol. If you could decipher the Tx part, I can try to implement it on the Nucleo. I would definitely need help, so yeah a communication channel is required.

Please also consider the GithubIssues as opposed to external tools. Here you can create me an issue, I ask questions inthe comments and you can reply back. The advantage of GitHub Issues is that we can readily use it without the need for an external tool for a place to collaborate. What do you think?

**Comment by trteodor** [comment]
Sure, for now we can keep communication here, and if it will be required then we can create new issues.

To understand a little better DLT protocool in my mind fristly you can read this document:
https://github.com/trteodor/DLTuc_lib/blob/master/docs/AUTOSAR_PRS_DiagnosticLogAndTraceProtocol.pdf

Hmm, my suggestion for you for now is to try run the library on your hardware, check a little implementation then please back to me with next questions. Tx header part is created in function (https://github.com/trteodor/DLTuc_lib/blob/master/src/DLTuc.c) **PrepareHoleHeader** currently in easiest possible way ;) .

**Comment by trteodor** [comment]
Hi nirmalnirav,
What is your progress? Did you successfully run the library on your hardware?

**Comment by nirmalnirav** [comment]
Hello Teodor,
- yes, I could successfully port the library to the STM32U575ZI series of Microcontroller. I could successfully test the example `example/simple` from the library and see the DLT messages populate in the DLT Viewer. It works!
- I also studied the library and its internal working. I am in the position to extend the library for the Rx function.
- I studied the DLT protocol. My goal is to implement the section `2.1.3 Use Case runtime configuration of Dlt` in the library. The section `5.3 Services / Commands`  lists the possible commands that fall under the scheme of sec 2.1.3.
- Unfortunately, all the commands falling under the schema of 2.1.3 are predefined and limited in scope.
- The only command that can do the "trick" given under the section `5.3.18 Call SWC Injection`. Here I have the provision to send any byte stream and the data size.
- **Question**: How to actually achieve this in the DLT Viewer? I see the item under `DLT -> Send injection`. Does this invoke the service from the section 5.3.18? 
- How do you see this work during the real world debugging? Does this mean that the developer have to click on the menu `DLT -> Send Injection` every time he wishes to send a UART message to the target? Usually in the terminal emulator like Putty, the Tx and the Rx messages can be entered without extra clicking/ handling. If a similar functionality is not given in the DLT Viewer, then it is a **show stopper.** 

Looking forward to read from you.

**Comment by trteodor** [comment]
Hi nirmalnirav,

Unfornatelly, without modification of DLT Viewer it will be difficult, from the second side DLT Viewer it is an open source application written in QT. I'm familiar a little(maybe a bit more than just a little) with QT framework, and I want just say that modyfication of DLT Veiwer shouldn't be difficult. I was even able to manage application a bit similar to DLT Viewer by my self:
https://github.com/trteodor/LineFollower_Light/blob/master/60_Pictures/QT_servApplScreenShotEx.jpg  (obvisuly much much simpler but the idea is well known for me). Serial data was also received to Qtable.

Please try implement the handler of injection messages, or generally receive handler. Then we can consider how to deal with it, or how to improve DLT Viewer. Please also consider implementation in form of callback registration function - which will be used to broadcast received injection message to application. 

**Despite some difficulties - you are right, it should be very useful to control / perform some additional tests of the application. Please go on with it, it's good idea!**

**Comment by trteodor** [comment]
Hi nirmalnirav,
Are you still planning to contribute? If you need any support from my side then please ask me directly here or via e-mail. 

Best regards,
Teodor

**Comment by trteodor** [comment]
Hello, 
I just pushed some updates,
Please check branch: https://github.com/trteodor/DLTuc_lib/tree/InjectionMsg , example: "simple"

I'm now able to transmit DLT messages from MCU and Receive the Injection messages in STM32 MCU, from the DLT Viewer.

![image](https://github.com/trteodor/DLTuc_lib/assets/79996579/7e127d63-0bab-4caa-acd7-3f50f107414a)

I had some free time in last days, I was bored then added the support. Please let me know if it is something what you expected.

**Comment by nirmalnirav** [comment]
Hello,
thanks for the update. Let me see this the upcoming weekend.

**Comment by nirmalnirav** [comment]
Hello,
I confirm this. Thanks for implementing it. :+1:
